apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-db
  template:
    metadata:
      labels:
        app: api-db
    spec:
      containers:
        - name: api-db
          image: localhost:4000/api-db
          ports:
            - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-db
  labels:
    app: api-db
spec:
  selector:
    app: api-db
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  type: LoadBalancer