apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-con
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-con
  template:
    metadata:
      labels:
        app: db-con
    spec:
      containers:
        - name: db-con
          image: localhost:4000/db-con
          ports:
            - containerPort: 5001
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: db-con
  labels:
    app: db-con
spec:
  selector:
    app: db-con
  ports:
    - name: "con-port"
      port: 5001
      targetPort: 5001
  type: LoadBalancer