apiVersion: v1
kind: Service
metadata:
  name: datab
  labels:
    app: datab
spec:
  ports:
  - name: "db-port"
    port: 3306
    targetPort: 3306
  selector:
    app: datab
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datab
  labels:
    app: datab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: datab
    spec:
      containers:
      - image: localhost:4000/mysql-db
        name: datab
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: datab
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_USER
          value: user
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim